# Generated by Django 3.1.5 on 2021-09-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=100)),
                ('valor', models.CharField(max_length=20)),
                ('qtd', models.CharField(max_length=20)),
                ('image', models.FileField(blank=True, upload_to='static/')),
            ],
        ),
    ]
