# Generated by Django 3.1.5 on 2021-09-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.TextField(max_length=100)),
                ('valor', models.CharField(max_length=20)),
                ('qtd', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='qtd',
        ),
    ]
