# Generated by Django 3.1.5 on 2021-09-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20210905_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='chave',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
