# Generated by Django 3.1.5 on 2021-09-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_carrinho_chave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=100)),
                ('nome', models.TextField(max_length=100)),
                ('pagamento', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='chave',
            field=models.CharField(max_length=100),
        ),
    ]
