# Generated by Django 3.1.5 on 2021-09-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_auto_20210907_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='qtd',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
