# Generated by Django 3.1.5 on 2021-09-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_auto_20210909_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='qtd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='valor',
            field=models.FloatField(),
        ),
    ]
