# Generated by Django 3.1.5 on 2021-09-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_auto_20210919_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='promocao',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
